mysite/urls.py
from django.conf.urls import *
from mysite import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
# admin.autodiscover()
#from django.contrib import admin
#admin.autodiscover()
urlpatterns = patterns('mysite.views',
('^hello/$','hello'),('^time/$','current_datetime'),(r'^time/plus/(\d{1,2})/$','hours_ahead')
,('^dog/$','dog'),('^go/$','go'),('^display/$','display_meta'),
('^dis/$','display'),(r'^search/$','search'),(r'^contact/$','contact'),
(r'^contact/thanks/$','success'), ,(r'^admin/', include(admin.site.urls)),)
# Examples:    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

books/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __unicode__(self):
        return self.name
class Student(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    city= models.CharField(max_length=60)

    def __unicode_(self):
        return self.name
class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField('e--mail',blank=True)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True )

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Poll(models.Model):
	question=models.CharField(max_length =200)
	pub_date = models.DateTimeField('date published')
	def __unicode__(self):
		return self.question
	def was_published_recently(self):
		return self.pub_date >=timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice = models.CharField(max_length=200)
	votes = models.IntegerField()
	def __unicode__(self):
		return self.choice

mysite/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False)
    message =forms.CharField(widget=forms.Textarea)
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words= len(message.split())
        if num_words<2:
            raise forms.ValidationError("Not enough words")
        return message

books/views.py
# Create your views here.

mysite/views.py
from django.shortcuts import render
from mysite.forms import ContactForm
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from books.models import Book
from mysite.models import MyModel
from django.core.mail import send_mail
#from django.http import HttpResponse,Http404
import datetime
def hello(request):
	return HttpResponse("Welcome to the page at %s" %request.get_host())
#        return	display_meta;
def go(request):
	ua = request.META.get('HTTP-USER-AGENT','UNKNOW')
	return HttpResponse("YOUR brower is %s" %ua)
def current_datetime(request):
	current_datetime = datetime.datetime.now()
	return render_to_response('current_datetime.html',locals())
def hours_ahead(request,offset):
	try:
		hours_offset = int(offset)
	except ValueError:
		raise Http404()
	next_time = datetime.datetime.now()+datetime.timedelta(hours=hours_offset)
	return render_to_response("hours_ahead.html",locals())	
def dog(request):
	dog = datetime.datetime.now()
	return render_to_response("dog.html",locals())


def display_meta(request):
	values=request.META.items()
	values.sort()
	html=[]
	for k,v in values:
		html.append('<tr><td>%s</td><td>v</td></tr>' %(k,v))
	return HttpResponse('<table>%s</table>' %'\n'.join(html))	

def display(request):
	values = request.GET
	return render_to_response("display.html",{"values":values})



def search(request):
    errors = []
    if 'q' in request.GET:
	q = request.GET['q']
        if not q:
                errors.append('Enter a search term.')
	elif len(q)>20:
		errors.append('Please enter at most 20 characters.')
        else:
		books = Book.objects.filter(authors__icontains=q)
		return render(request,'search_result.html',{'books':books,'query':q})
    return render(request,'search_form.html',{'errors':errors})


def contact(request):
    if request.method=='POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('hongbayu@163.com'),
                ['hongbayu@163.com'],
            )
            return HttpResponseRedirect('/contact/thanks')
    else:
        form = ContactForm(
		initial={'subject':'I love you'}
	)
    return render(request,'contact_form.html',{'form':form})


def success(request):
    return render(request,'thanks.html')

def foo(*args,**kwargs):
    print "Positional arguments are:"
    print args
    print "keyword arguments are:"
    print kwargs

polls/views.py
# Create your views here.

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<title>{%block title%}{%endblock%}</title>
</head>

<body>
	<h1>My helpful timestamp site.Douban</h1>
	{%block content%}{%endblock%}
	{%block footer%}
	<hr>
	<p>I am the base html</p>
	{%endblock%}


</body>
</html>

templates/contact_form.html
<html>
    <head>
        <title>Contact us</title>
        
    </head>
    <style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>
    <body>
        <h1>Contact us</h1>
    <div class="field" {%if form.message.errors%}errors{% endif %}>
        <ul>
        {%for error in form.message.errors%}
            <li><strong>{{error}}</strong></li>
        {% endfor %}
        </ul>
    {%endif%}
   
        </div>
        <form action="" method="post">
          <div class="field">
            {{form.subject.errors}}
            <label for="id_subject">Subject:</label>
            {{form.subject}}
            
          </div>
          
          <div class="field">
            {{form.email.errors}}
            <label for="id_email">Your e-mail address:</label>
            {{form.email}}
          </div>
          
          <div class="field">
            {{form.message.errors}}
            <label for="id_message">Message:</label>
            {{form.message}}
          </div>
            <input type = "submit" value="Submit">
        </form>
    </body>
</html>

templates/current_datetime.html
{% extends "base.html" %}

{% block title %} Current_time{% endblock %}

{% block content %}

<p>It is now {{current_datetime}}</p>
{% endblock %}
{% block footer %}
<p>This is the begin site</p>
{{block.super}}
<p>This is the end site</p>
{%endblock%}

templates/display.html
{% extends "base.html" %}

{% block title%}Display Information {%endblock%}

{%block content%}
<table id=showmeta>


{%for key in values%}
<tr>
<td>{{key}}</td>
</tr>
{%endfor%}

</table>
{%endblock%}

templates/dog.html
{%block title%}<h1>I am a dog</h1>{%endblock%}

{%block content%}<p>Call me hashmap</p>{%endblock%}

{%block footer%}<p>We are all good dog{{dog}}</p>{%endblock%}

templates/hours_ahead.html
{% extends "base.html" %}
{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{hours_offset}},it will be {{next_time}}</p>
{% endblock %}

templates/new.html
<html>
    <head>
    </head>

    <body>
Auto-escaping is on by default Hello{{name}}

{% autoescape off %}

    This will not be auto-auto-escaped{{data}}
    { %autoescape on %}
    Auto-escaping applied again:{{name}}
    {% endautoescape %}
{% endautoescape %}
</body>
</html>

templates/search_form.html
<html>
<head>
	<title>Search</title>
              	
</head>

<body>
    {%if errors%}
	    <ul>
		{%for error in errors%}
			<li>{{error}}</li>
		{%endfor%}
	    </ul>
    {%endif%}
	<form action="" method="get">
	    <input type="text" name="q">
	    <input type="submit" value="search">
	</form>
</body>
</html>

templates/search_result.html
<html>
<head>
<title>
Your father
</title>
</head>
<body>
<p>You searched for: <strong>{{query}}</strong></p>

{% if books% }
    <p> Found {{ books|length }}book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
	<li>{{ book.authors }}</li>
	{% endfor %}

    </ul>
{%else%}
    <p>No books matched your search criteria.</p>

{% endif %}

</body>
</html>

templates/thanks.html
<html>
<head>
    <title>
    {%block title%}
    Congratulations
    {%endblock%}
    </title>
</head>
<body>{%block content%}
    <h1>You have successfuly send a email</h1>
     {%endblock%}
</body>
</html>